rule_files:
  - "alert-rules.yml"

scrape_configs:
  - job_name: 'node_exporter and cadvisor'

    # Override the global default and scrape targets from this job every 5 seconds.
    scrape_interval: 5s

    static_configs:
      - targets: ['c_advisor:8080']
        labels:
          group: 'c_advisor'
      - targets: ['node_exporter:9100']
        labels:
          group: 'node_exporter'


alerting:
  alertmanagers:
  - static_configs:
    - targets: ['alert_manager:9093']

# alerting:
#   alertmanagers:
#     - scheme: http
#       path_prefix: /alertmanager
#       static_configs:
#         - targets: ['172.18.0.3:9093']
